apiVersion: v1 
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPol: 80
  selector:
    app: ngins
  type: LoadBalancer        